/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author User
 */
public class Tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_principal
     */
    public Tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_fotos = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar8 = new javax.swing.JToolBar();
        exit = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        tela_funcionarios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        produtos = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        venda = new javax.swing.JLabel();
        vendidos = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        rua = new javax.swing.JLabel();
        tipotelefone = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 426));
        setMinimumSize(new java.awt.Dimension(650, 426));
        setPreferredSize(new java.awt.Dimension(650, 426));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 426));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Tela princiapal");

        jToolBar8.setRollover(true);
        jToolBar8.setBorderPainted(false);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exit-64.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jToolBar8.add(exit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jb_fotos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jb_fotos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addComponent(jToolBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 67);

        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);

        tela_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eu-iria.png"))); // NOI18N
        tela_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tela_funcionariosMouseClicked(evt);
            }
        });
        jToolBar1.add(tela_funcionarios);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 107, 36, 47);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 160, 650, 10);

        jSeparator2.setToolTipText("");
        jSeparator2.setName(""); // NOI18N
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(6, 272, 644, 10);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("produtos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 294, 110, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("cidade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 190, 81, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel18.setText("Cliente");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(6, 188, 81, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel19.setText("Estado");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(90, 190, 81, 25);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel20.setText("telefone");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(540, 190, 120, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel21.setText("Bairro");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(260, 190, 81, 25);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel22.setText("rua");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(340, 190, 81, 25);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel23.setText("tipo telefone");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(390, 190, 180, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("funcionario");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 73, 150, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Cradastro ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 334, 100, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Tipo:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(117, 334, 70, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("venda");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 334, 70, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setText("marca");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(205, 334, 70, 25);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel16.setText("vendidos:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(406, 334, 100, 25);

        produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar-produto.png"))); // NOI18N
        produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosMouseClicked(evt);
            }
        });
        getContentPane().add(produtos);
        produtos.setBounds(60, 357, 32, 32);

        tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addition.png"))); // NOI18N
        tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoMouseClicked(evt);
            }
        });
        getContentPane().add(tipo);
        tipo.setBounds(149, 357, 32, 32);

        marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-square-brackets-32.png"))); // NOI18N
        marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marcaMouseClicked(evt);
            }
        });
        getContentPane().add(marca);
        marca.setBounds(250, 357, 32, 32);

        venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crescimento.png"))); // NOI18N
        venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendaMouseClicked(evt);
            }
        });
        getContentPane().add(venda);
        venda.setBounds(349, 357, 32, 32);

        vendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-finalizar-pedido-32.png"))); // NOI18N
        vendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendidosMouseClicked(evt);
            }
        });
        getContentPane().add(vendidos);
        vendidos.setBounds(478, 349, 32, 32);

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
        });
        getContentPane().add(cliente);
        cliente.setBounds(20, 220, 32, 32);

        estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estados-unidos.png"))); // NOI18N
        estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadoMouseClicked(evt);
            }
        });
        getContentPane().add(estado);
        estado.setBounds(100, 220, 32, 32);

        bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cidade-verde.png"))); // NOI18N
        bairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bairroMouseClicked(evt);
            }
        });
        getContentPane().add(bairro);
        bairro.setBounds(270, 220, 32, 40);

        cidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cidade.png"))); // NOI18N
        cidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cidadeMouseClicked(evt);
            }
        });
        getContentPane().add(cidade);
        cidade.setBounds(200, 220, 32, 40);

        rua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rua.png"))); // NOI18N
        rua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ruaMouseClicked(evt);
            }
        });
        getContentPane().add(rua);
        rua.setBounds(340, 220, 32, 32);

        tipotelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/responsivo.png"))); // NOI18N
        tipotelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipotelefoneMouseClicked(evt);
            }
        });
        getContentPane().add(tipotelefone);
        tipotelefone.setBounds(440, 230, 40, 30);

        telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefones.png"))); // NOI18N
        telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefoneMouseClicked(evt);
            }
        });
        getContentPane().add(telefone);
        telefone.setBounds(570, 230, 32, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tela_funcionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tela_funcionariosMouseClicked
        // TODO add your handling code here:
      tela_funcionario objtel = new tela_funcionario();
      objtel.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_tela_funcionariosMouseClicked

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteMouseClicked

    private void produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_produtosMouseClicked

    private void vendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vendaMouseClicked

    private void tipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMouseClicked

    private void marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaMouseClicked

    private void vendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vendidosMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:

      this.dispose();
        
    }//GEN-LAST:event_exitMouseClicked

    private void estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoMouseClicked

    private void bairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bairroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroMouseClicked

    private void cidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeMouseClicked

    private void ruaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaMouseClicked

    private void tipotelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipotelefoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tipotelefoneMouseClicked

    private void telefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairro;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar8;
    private javax.swing.JLabel jb_fotos;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel produtos;
    private javax.swing.JLabel rua;
    private javax.swing.JLabel tela_funcionarios;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel tipotelefone;
    private javax.swing.JLabel venda;
    private javax.swing.JLabel vendidos;
    // End of variables declaration//GEN-END:variables

    public void limpar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
